default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: clever_calculator_development

test:
  <<: *default
  database: clever_calculator_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
