default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: clever_calculator_development

test:
  <<: *default
  database: clever_calculator_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
